version: '3.8'

services:
  app:
    build: .
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/db_usuario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db  #-db garante que o banco de dados seja iniciado antes da aplicação, para não ter erro de conexão.

  db:
    image: postgres:latest   # latest = pra ser ultima versão do Postgres
    environment:
      POSTGRES_DB: db_usuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"