spring.application.name=usuario

spring.datasource.url=jdbc:postgresql://localhost:5433/db_usuario
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8083

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
